INFO 2025-02-26 09:38:44,359 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:39:35,420 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
WARNING 2025-02-26 09:39:53,722 log Unauthorized: /users/api/logout/
WARNING 2025-02-26 09:39:53,722 basehttp "POST /users/api/logout/ HTTP/1.1" 401 27
INFO 2025-02-26 09:40:05,904 basehttp "POST /users/api/login/ HTTP/1.1" 200 149
INFO 2025-02-26 09:45:28,036 autoreload C:\Users\User\Desktop\docs\taskmanager\users\views.py changed, reloading.
INFO 2025-02-26 09:45:28,636 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:45:36,399 views Ползователь пытается войти
INFO 2025-02-26 09:45:37,037 views Ползователь с test21@gmail.com паролем pbkdf2_sha256$870000$fpkE532rQqi8NV6QDwUFIb$ZPFFqngBrY7jV9gbPi2MYRXLOJBrMO1ctt1YaRDQMKw= вошел на сайт 13
INFO 2025-02-26 09:45:37,037 views Ползователь с test21@gmail.com паролем pbkdf2_sha256$870000$fpkE532rQqi8NV6QDwUFIb$ZPFFqngBrY7jV9gbPi2MYRXLOJBrMO1ctt1YaRDQMKw= вошел на сайт 13
INFO 2025-02-26 09:45:37,065 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
INFO 2025-02-26 09:47:01,988 autoreload C:\Users\User\Desktop\docs\taskmanager\users\views.py changed, reloading.
INFO 2025-02-26 09:47:02,651 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 09:47:12,204 log Method Not Allowed: /users/api/login/
WARNING 2025-02-26 09:47:12,204 basehttp "GET /users/api/login/ HTTP/1.1" 405 5598
INFO 2025-02-26 09:47:31,083 views Ползователь пытается войти
INFO 2025-02-26 09:47:31,739 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:47:31,739 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:47:31,742 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
INFO 2025-02-26 09:49:40,507 views Ползователь пытается войти
ERROR 2025-02-26 09:49:41,187 log Internal Server Error: /users/api/login/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\taskmanager\users\views.py", line 71, in post
    logger.warning(f'Неудачный вход {user.email} неверные данные')
                                     ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email'
ERROR 2025-02-26 09:49:41,190 basehttp "POST /users/api/login/ HTTP/1.1" 500 97006
WARNING 2025-02-26 09:49:51,752 log Method Not Allowed: /users/api/login/
WARNING 2025-02-26 09:49:51,752 basehttp "GET /users/api/login/ HTTP/1.1" 405 5598
INFO 2025-02-26 09:49:57,785 views Ползователь пытается войти
INFO 2025-02-26 09:49:58,434 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:49:58,434 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:49:58,437 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
INFO 2025-02-26 09:50:38,051 autoreload C:\Users\User\Desktop\docs\taskmanager\users\views.py changed, reloading.
INFO 2025-02-26 09:50:38,846 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:50:47,792 views Ползователь пытается войти
INFO 2025-02-26 09:50:48,449 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:50:48,449 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:50:48,474 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
INFO 2025-02-26 09:51:03,435 autoreload C:\Users\User\Desktop\docs\taskmanager\users\views.py changed, reloading.
INFO 2025-02-26 09:51:04,094 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:51:10,116 views Ползователь пытается войти
INFO 2025-02-26 09:51:10,782 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:51:10,782 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:51:10,809 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
INFO 2025-02-26 09:51:20,087 autoreload C:\Users\User\Desktop\docs\taskmanager\users\views.py changed, reloading.
INFO 2025-02-26 09:51:20,761 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 09:51:25,277 views Ползователь пытается войти
INFO 2025-02-26 09:51:25,927 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:51:25,927 views Ползователь с test21@gmail.com вошел на сайт 13
INFO 2025-02-26 09:51:25,959 basehttp "POST /users/api/login/ HTTP/1.1" 200 5682
INFO 2025-02-26 10:07:50,796 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:07:51,846 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 27213
INFO 2025-02-26 10:07:51,952 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:08:30,725 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 10:08:31,588 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:08:58,081 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:10:02,534 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 10:10:03,225 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:10:28,575 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 10:10:29,839 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:11:03,627 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 10:11:04,834 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:11:08,540 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 31137
INFO 2025-02-26 10:11:08,657 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:12,430 basehttp "GET /admin/tasks/task/?priority__exact=%D0%A1%D0%A0%D0%95%D0%94%D0%9D%D0%98%D0%99 HTTP/1.1" 200 24982
INFO 2025-02-26 10:11:12,501 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:16,628 basehttp "GET /admin/tasks/task/?priority__exact=%D0%9A%D0%A0%D0%98%D0%A2%D0%98%D0%A7%D0%95%D0%A1%D0%9A%D0%98%D0%99 HTTP/1.1" 200 25022
INFO 2025-02-26 10:11:16,701 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:19,115 basehttp "GET /admin/tasks/task/?priority__exact=%D0%92%D0%AB%D0%A1%D0%9E%D0%9A%D0%98%D0%99 HTTP/1.1" 200 24982
INFO 2025-02-26 10:11:19,286 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:21,426 basehttp "GET /admin/tasks/task/?priority__exact=%D0%A1%D0%A0%D0%95%D0%94%D0%9D%D0%98%D0%99 HTTP/1.1" 200 24982
INFO 2025-02-26 10:11:21,500 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:24,093 basehttp "GET /admin/tasks/task/? HTTP/1.1" 200 31137
INFO 2025-02-26 10:11:24,168 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:28,094 basehttp "GET /admin/tasks/task/?status__exact=%D0%90%D0%9A%D0%A2%D0%98%D0%92%D0%95%D0%9D HTTP/1.1" 200 32047
INFO 2025-02-26 10:11:28,167 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:31,374 basehttp "GET /admin/tasks/task/?status__exact=%D0%92+%D0%9F%D0%A0%D0%9E%D0%A6%D0%95%D0%A1%D0%A1%D0%95 HTTP/1.1" 200 25003
INFO 2025-02-26 10:11:31,451 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:34,143 basehttp "GET /admin/tasks/task/? HTTP/1.1" 200 31137
INFO 2025-02-26 10:11:34,323 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:35,641 basehttp "GET /admin/tasks/task/1/change/ HTTP/1.1" 200 37364
INFO 2025-02-26 10:11:35,724 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:46,316 basehttp "POST /admin/tasks/task/1/change/ HTTP/1.1" 302 0
INFO 2025-02-26 10:11:46,399 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 31696
INFO 2025-02-26 10:11:46,469 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:49,998 basehttp "GET /admin/tasks/task/?priority__exact=%D0%9A%D0%A0%D0%98%D0%A2%D0%98%D0%A7%D0%95%D0%A1%D0%9A%D0%98%D0%99 HTTP/1.1" 200 29937
INFO 2025-02-26 10:11:50,186 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:55,112 basehttp "GET /admin/tasks/task/?status__exact=%D0%92+%D0%9F%D0%A0%D0%9E%D0%A6%D0%95%D0%A1%D0%A1%D0%95&priority__exact=%D0%9A%D0%A0%D0%98%D0%A2%D0%98%D0%A7%D0%95%D0%A1%D0%9A%D0%98%D0%99 HTTP/1.1" 200 30614
INFO 2025-02-26 10:11:55,291 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:11:57,476 basehttp "GET /admin/tasks/task/?status__exact=%D0%92+%D0%9F%D0%A0%D0%9E%D0%A6%D0%95%D0%A1%D0%A1%D0%95 HTTP/1.1" 200 29821
INFO 2025-02-26 10:11:57,653 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:12:01,711 basehttp "GET /admin/tasks/task/?status__exact=%D0%90%D0%9A%D0%A2%D0%98%D0%92%D0%95%D0%9D HTTP/1.1" 200 31568
INFO 2025-02-26 10:12:01,786 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:12:05,583 basehttp "GET /admin/tasks/task/? HTTP/1.1" 200 31137
INFO 2025-02-26 10:12:05,661 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-02-26 10:12:21,838 log Method Not Allowed: /users/api/login/
WARNING 2025-02-26 10:12:21,838 basehttp "GET /users/api/login/ HTTP/1.1" 405 5598
INFO 2025-02-26 10:12:46,054 basehttp "GET /admin/chat/chat/ HTTP/1.1" 200 22770
INFO 2025-02-26 10:12:46,132 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:12:55,193 basehttp "GET /admin/tasks/task_comments/ HTTP/1.1" 200 25462
INFO 2025-02-26 10:12:55,270 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:13:02,605 basehttp "GET /admin/tasks/projects/ HTTP/1.1" 200 26582
INFO 2025-02-26 10:13:02,682 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:14:00,584 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 10:14:01,500 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:14:02,343 basehttp "GET /admin/tasks/projects/ HTTP/1.1" 200 27460
INFO 2025-02-26 10:14:02,521 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:14:15,897 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 23015
INFO 2025-02-26 10:14:15,983 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:15:54,538 autoreload C:\Users\User\Desktop\docs\taskmanager\event_calendar\admin.py changed, reloading.
INFO 2025-02-26 10:15:55,197 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:15:56,053 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 23015
INFO 2025-02-26 10:15:56,138 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:21:04,726 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 23015
INFO 2025-02-26 10:21:04,818 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:21:20,323 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 23015
INFO 2025-02-26 10:21:20,430 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:21:20,699 autoreload C:\Users\User\Desktop\docs\taskmanager\event_calendar\admin.py changed, reloading.
INFO 2025-02-26 10:21:21,629 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:21:22,476 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 25214
INFO 2025-02-26 10:21:22,545 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:21:28,053 basehttp "GET /admin/event_calendar/event/?event_type__exact=%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%95 HTTP/1.1" 200 25475
INFO 2025-02-26 10:21:28,125 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:21:40,507 autoreload C:\Users\User\Desktop\docs\taskmanager\event_calendar\admin.py changed, reloading.
INFO 2025-02-26 10:21:41,486 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:21:42,401 basehttp "GET /admin/event_calendar/event/?event_type__exact=%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%95 HTTP/1.1" 200 26928
INFO 2025-02-26 10:21:42,472 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:24:06,008 basehttp "GET /admin/news/news/ HTTP/1.1" 200 26819
INFO 2025-02-26 10:24:06,099 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:24:42,383 basehttp "GET /admin/news/news/ HTTP/1.1" 200 26819
INFO 2025-02-26 10:24:42,445 autoreload C:\Users\User\Desktop\docs\taskmanager\news\admin.py changed, reloading.
INFO 2025-02-26 10:24:43,134 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:24:43,958 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:24:45,043 basehttp "GET /admin/news/news/ HTTP/1.1" 200 30427
INFO 2025-02-26 10:24:45,233 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:25:00,626 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22419
INFO 2025-02-26 10:25:00,710 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:25:36,248 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:25:36,988 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:25:57,965 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:25:58,576 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:26:06,473 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:26:07,125 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:26:08,167 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22419
INFO 2025-02-26 10:26:08,275 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:26:29,136 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:26:29,885 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:26:30,715 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22419
INFO 2025-02-26 10:26:30,896 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:26:33,388 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22419
INFO 2025-02-26 10:26:33,457 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:26:35,363 basehttp "GET /admin/notifications/notification/1/change/ HTTP/1.1" 200 26327
INFO 2025-02-26 10:26:35,536 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:26:42,817 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22419
INFO 2025-02-26 10:26:42,988 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:26:48,438 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22419
INFO 2025-02-26 10:26:48,607 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:26:48,768 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:26:49,371 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:26:50,107 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 22874
INFO 2025-02-26 10:26:50,178 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:27:20,913 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:27:21,604 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:27:30,826 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:27:31,656 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:27:37,751 autoreload C:\Users\User\Desktop\docs\taskmanager\notifications\admin.py changed, reloading.
INFO 2025-02-26 10:27:38,641 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:27:39,633 basehttp "GET /admin/notifications/notification/ HTTP/1.1" 200 24210
INFO 2025-02-26 10:27:39,765 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:27:44,288 basehttp "GET /admin/notifications/notification/?notification_type__exact=%D0%94%D0%9E%D0%A1%D0%A2%D0%98%D0%96%D0%95%D0%9D%D0%98%D0%95 HTTP/1.1" 200 22533
INFO 2025-02-26 10:27:44,360 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:27:51,433 basehttp "GET /admin/chat/chat/ HTTP/1.1" 200 22770
INFO 2025-02-26 10:27:51,506 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:27:55,472 basehttp "GET /admin/chat/messages/ HTTP/1.1" 200 25380
INFO 2025-02-26 10:27:55,551 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:27:58,743 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 26638
INFO 2025-02-26 10:27:58,817 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:28:28,374 autoreload C:\Users\User\Desktop\docs\taskmanager\event_calendar\admin.py changed, reloading.
INFO 2025-02-26 10:28:28,997 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:28:29,945 basehttp "GET /admin/event_calendar/event/ HTTP/1.1" 200 28642
INFO 2025-02-26 10:28:30,016 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:49:58,245 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 10:50:02,198 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:50:21,433 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:50:27,564 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 31137
INFO 2025-02-26 10:50:27,677 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:50:33,152 basehttp "GET /admin/tasks/task/1/change/ HTTP/1.1" 200 38266
INFO 2025-02-26 10:50:33,240 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:50:42,346 basehttp "POST /admin/tasks/task/1/change/ HTTP/1.1" 302 0
INFO 2025-02-26 10:50:42,557 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 31696
INFO 2025-02-26 10:50:42,639 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:51:10,544 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 10:51:11,436 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 10:51:13,624 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 32556
INFO 2025-02-26 10:51:13,750 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 10:51:16,781 basehttp "GET /admin/tasks/task/?agreed_with_managers__exact=1 HTTP/1.1" 200 30587
INFO 2025-02-26 10:51:16,858 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 11:09:20,535 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 11:19:30,443 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 11:19:37,548 log Not Found: /
WARNING 2025-02-26 11:19:37,550 basehttp "GET / HTTP/1.1" 404 3064
ERROR 2025-02-26 11:19:43,463 log Internal Server Error: /users/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\docs\taskmanager\users\views.py", line 26, in index_view
    return render(request, "dist/index.html", {})
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dist/index.html
ERROR 2025-02-26 11:19:43,466 basehttp "GET /users/ HTTP/1.1" 500 87422
INFO 2025-02-26 11:24:04,402 basehttp "GET /users/ HTTP/1.1" 200 123
WARNING 2025-02-26 11:24:45,843 log Method Not Allowed (GET): /users/login/
WARNING 2025-02-26 11:24:45,844 basehttp "GET /users/login/ HTTP/1.1" 405 0
WARNING 2025-02-26 11:24:49,603 log Method Not Allowed (GET): /users/login/
WARNING 2025-02-26 11:24:49,604 basehttp "GET /users/login/ HTTP/1.1" 405 0
ERROR 2025-02-26 11:25:30,220 exception Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 11:25:30,296 log Bad Request: /
WARNING 2025-02-26 11:25:30,297 basehttp "GET / HTTP/1.1" 400 72638
ERROR 2025-02-26 11:25:30,605 exception Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 11:25:30,621 log Bad Request: /favicon.ico
WARNING 2025-02-26 11:25:30,622 basehttp "GET /favicon.ico HTTP/1.1" 400 72563
INFO 2025-02-26 11:28:26,073 autoreload C:\Users\User\Desktop\docs\taskmanager\users\urls.py changed, reloading.
INFO 2025-02-26 11:28:26,826 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 11:28:28,830 log Not Found: /
WARNING 2025-02-26 11:28:28,832 basehttp "GET / HTTP/1.1" 404 3064
INFO 2025-02-26 11:28:29,948 autoreload C:\Users\User\Desktop\docs\taskmanager\users\views.py changed, reloading.
INFO 2025-02-26 11:28:30,537 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 11:29:18,792 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 11:29:21,431 log Not Found: /
WARNING 2025-02-26 11:29:21,432 basehttp "GET / HTTP/1.1" 404 3064
WARNING 2025-02-26 11:29:28,984 log Not Found: /users/
WARNING 2025-02-26 11:29:28,985 basehttp "GET /users/ HTTP/1.1" 404 4195
INFO 2025-02-26 11:29:34,612 basehttp "GET /users/api/users/ HTTP/1.1" 200 11950
INFO 2025-02-26 11:30:11,947 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 11:30:12,471 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 11:31:13,876 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 11:31:43,324 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 11:31:43,999 autoreload Watching for file changes with StatReloader
ERROR 2025-02-26 11:40:38,583 exception Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2025-02-26 11:40:38,611 log Bad Request: /favicon.ico
WARNING 2025-02-26 11:40:38,611 basehttp "GET /favicon.ico HTTP/1.1" 400 72842
INFO 2025-02-26 11:43:37,549 basehttp "GET /admin/tasks/task/?agreed_with_managers__exact=1 HTTP/1.1" 200 30587
WARNING 2025-02-26 12:11:43,131 log Not Found: /favicon.ico
WARNING 2025-02-26 12:11:43,134 basehttp "GET /favicon.ico HTTP/1.1" 404 3115
WARNING 2025-02-26 15:23:16,667 log Not Found: /
WARNING 2025-02-26 15:23:16,671 basehttp "GET / HTTP/1.1" 404 3064
WARNING 2025-02-26 15:23:16,989 log Not Found: /favicon.ico
WARNING 2025-02-26 15:23:16,990 basehttp "GET /favicon.ico HTTP/1.1" 404 3115
INFO 2025-02-26 15:23:22,075 basehttp "GET /tasks/ HTTP/1.1" 200 447
INFO 2025-02-26 15:23:32,411 basehttp "GET /tasks/tasks/ HTTP/1.1" 200 10586
INFO 2025-02-26 15:39:06,085 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:39:10,234 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:39:21,149 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:39:21,802 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:42:14,043 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:42:15,140 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:42:29,592 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:42:30,310 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:43:10,597 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:43:11,269 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:43:18,710 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:43:19,232 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:43:28,675 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:43:29,555 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:43:37,144 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:43:37,745 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 15:49:03,913 autoreload Watching for file changes with StatReloader
ERROR 2025-02-26 15:49:06,625 log Internal Server Error: /tasks/tasks/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: ОШИБКА:  столбец tasks_task.status_id не существует
LINE 1: ...asks_task"."start_date", "tasks_task"."end_date", "tasks_tas...
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "tasks_task.status".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  столбец tasks_task.status_id не существует
LINE 1: ...asks_task"."start_date", "tasks_task"."end_date", "tasks_tas...
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "tasks_task.status".

ERROR 2025-02-26 15:49:06,673 basehttp "GET /tasks/tasks/ HTTP/1.1" 500 175195
INFO 2025-02-26 15:49:14,120 basehttp "GET /admin/ HTTP/1.1" 200 49913
INFO 2025-02-26 15:49:14,137 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
ERROR 2025-02-26 15:49:17,330 log Internal Server Error: /admin/tasks/task/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: ОШИБКА:  отношение "tasks_status" не существует
LINE 1: ...tus"."status_name", "tasks_status"."user_id" FROM "tasks_sta...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.queryset = self.get_queryset(request)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 545, in get_queryset
    ) = self.get_filters(request)
        ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 216, in get_filters
    spec = field_list_filter_class(
        field,
    ...<4 lines>...
        field_path=field_path,
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
        field, request, params, model, model_admin, field_path=field_path
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1077, in get_choices
    (choice_func(x), str(x)) for x in qs
                                      ^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  отношение "tasks_status" не существует
LINE 1: ...tus"."status_name", "tasks_status"."user_id" FROM "tasks_sta...
                                                             ^

ERROR 2025-02-26 15:49:17,337 basehttp "GET /admin/tasks/task/ HTTP/1.1" 500 207776
INFO 2025-02-26 15:49:55,023 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 15:49:55,670 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:04:15,229 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:04:17,469 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 19861
INFO 2025-02-26 16:04:17,504 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,512 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,513 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,515 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,515 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,520 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,528 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-02-26 16:04:17,652 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:04:20,783 basehttp "GET /admin/tasks/task_comments/ HTTP/1.1" 200 19924
INFO 2025-02-26 16:04:20,875 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:04:29,188 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 16:04:30,041 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:04:37,314 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:04:37,910 autoreload Watching for file changes with StatReloader
ERROR 2025-02-26 16:05:03,964 log Internal Server Error: /admin/tasks/task/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: ОШИБКА:  отношение "tasks_status" не существует
LINE 1: ...tus"."status_name", "tasks_status"."user_id" FROM "tasks_sta...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.queryset = self.get_queryset(request)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 545, in get_queryset
    ) = self.get_filters(request)
        ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 216, in get_filters
    spec = field_list_filter_class(
        field,
    ...<4 lines>...
        field_path=field_path,
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
        field, request, params, model, model_admin, field_path=field_path
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1077, in get_choices
    (choice_func(x), str(x)) for x in qs
                                      ^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  отношение "tasks_status" не существует
LINE 1: ...tus"."status_name", "tasks_status"."user_id" FROM "tasks_sta...
                                                             ^

ERROR 2025-02-26 16:05:03,974 basehttp "GET /admin/tasks/task/ HTTP/1.1" 500 207796
INFO 2025-02-26 16:05:27,953 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:05:28,567 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:05:33,704 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 16:05:34,365 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:05:46,337 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 19861
INFO 2025-02-26 16:05:46,410 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:05:48,010 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 32832
INFO 2025-02-26 16:05:48,029 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,029 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,030 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,031 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,046 basehttp "GET /static/jazzmin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,052 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,055 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,059 basehttp "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,063 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-02-26 16:05:48,183 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:06:21,083 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:06:21,869 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:07:02,099 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\admin.py changed, reloading.
INFO 2025-02-26 16:07:03,014 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:07:04,069 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 33786
INFO 2025-02-26 16:07:04,208 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:07,103 basehttp "GET /admin/tasks/status/ HTTP/1.1" 200 20832
INFO 2025-02-26 16:07:07,273 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:30,654 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:07:31,358 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:07:32,226 basehttp "GET /admin/tasks/status/ HTTP/1.1" 200 20827
INFO 2025-02-26 16:07:32,397 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:35,633 basehttp "GET /admin/tasks/priority/ HTTP/1.1" 200 20841
INFO 2025-02-26 16:07:35,722 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:37,400 basehttp "GET /admin/tasks/priority/add/ HTTP/1.1" 200 24345
INFO 2025-02-26 16:07:37,574 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:48,394 basehttp "POST /admin/tasks/priority/add/ HTTP/1.1" 200 24659
INFO 2025-02-26 16:07:48,564 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:51,138 basehttp "POST /admin/tasks/priority/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:07:51,228 basehttp "GET /admin/tasks/priority/ HTTP/1.1" 200 23831
INFO 2025-02-26 16:07:51,303 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:07:57,190 basehttp "GET /admin/tasks/priority/add/ HTTP/1.1" 200 24345
INFO 2025-02-26 16:07:57,262 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:00,302 basehttp "POST /admin/tasks/priority/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:08:00,371 basehttp "GET /admin/tasks/priority/add/ HTTP/1.1" 200 24952
INFO 2025-02-26 16:08:00,474 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:05,880 basehttp "POST /admin/tasks/priority/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:08:05,971 basehttp "GET /admin/tasks/priority/add/ HTTP/1.1" 200 24952
INFO 2025-02-26 16:08:06,046 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:14,431 basehttp "POST /admin/tasks/priority/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:08:14,643 basehttp "GET /admin/tasks/priority/ HTTP/1.1" 200 25004
INFO 2025-02-26 16:08:14,718 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:17,573 basehttp "GET /admin/tasks/status/ HTTP/1.1" 200 20827
INFO 2025-02-26 16:08:17,645 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:28,249 basehttp "GET /admin/tasks/status/add/ HTTP/1.1" 200 24317
INFO 2025-02-26 16:08:28,324 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:31,622 basehttp "POST /admin/tasks/status/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:08:31,692 basehttp "GET /admin/tasks/status/add/ HTTP/1.1" 200 24923
INFO 2025-02-26 16:08:31,770 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:37,767 basehttp "POST /admin/tasks/status/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:08:37,946 basehttp "GET /admin/tasks/status/add/ HTTP/1.1" 200 24920
INFO 2025-02-26 16:08:38,035 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:08:56,528 basehttp "POST /admin/tasks/status/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:08:56,595 basehttp "GET /admin/tasks/status/ HTTP/1.1" 200 24588
INFO 2025-02-26 16:08:56,669 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:09:09,061 basehttp "GET /admin/tasks/status/add/ HTTP/1.1" 200 24317
INFO 2025-02-26 16:09:09,136 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:09:13,091 basehttp "POST /admin/tasks/status/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:09:13,159 basehttp "GET /admin/tasks/status/ HTTP/1.1" 200 24968
INFO 2025-02-26 16:09:13,233 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:10:07,585 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:10:08,203 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:10:24,876 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 20813
INFO 2025-02-26 16:10:25,006 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:10:26,374 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 38575
INFO 2025-02-26 16:10:26,545 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:10:51,012 basehttp "POST /admin/tasks/task/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:10:51,089 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 27180
INFO 2025-02-26 16:10:51,106 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
INFO 2025-02-26 16:10:51,161 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:24:35,250 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\serializers.py changed, reloading.
INFO 2025-02-26 16:24:36,165 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:24:50,830 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\serializers.py changed, reloading.
INFO 2025-02-26 16:24:51,574 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:24:55,363 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\serializers.py changed, reloading.
INFO 2025-02-26 16:24:56,065 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:25:09,560 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\serializers.py changed, reloading.
INFO 2025-02-26 16:25:10,258 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:27:33,306 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\urls.py changed, reloading.
INFO 2025-02-26 16:27:34,018 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:27:41,208 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 16:27:43,019 log Not Found: /
WARNING 2025-02-26 16:27:43,020 basehttp "GET / HTTP/1.1" 404 3064
INFO 2025-02-26 16:27:52,344 basehttp "GET /tasks/status/ HTTP/1.1" 200 5714
INFO 2025-02-26 16:36:22,998 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 38575
INFO 2025-02-26 16:36:23,098 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:38:37,790 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:38:38,399 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:38:38,723 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:38:39,100 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:38:46,939 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:38:47,298 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:38:47,836 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:38:47,973 autoreload Watching for file changes with StatReloader
ERROR 2025-02-26 16:39:08,451 log Internal Server Error: /admin/tasks/task/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: ОШИБКА:  столбец tasks_task.tags_id не существует
LINE 1: ...ks_task"."task_name", "tasks_task"."description", "tasks_tas...
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "tasks_task.tags" или столбец "tasks_task.status_id".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  столбец tasks_task.tags_id не существует
LINE 1: ...ks_task"."task_name", "tasks_task"."description", "tasks_tas...
                                                             ^
HINT:  Возможно, предполагалась ссылка на столбец "tasks_task.tags" или столбец "tasks_task.status_id".

ERROR 2025-02-26 16:39:08,458 basehttp "GET /admin/tasks/task/ HTTP/1.1" 500 180996
ERROR 2025-02-26 16:39:11,072 log Internal Server Error: /admin/tasks/task/add/
Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: ОШИБКА:  отношение "tasks_tags" не существует
LINE 1: ...T "tasks_tags"."id", "tasks_tags"."tag_name" FROM "tasks_tag...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: ОШИБКА:  отношение "tasks_tags" не существует
LINE 1: ...T "tasks_tags"."id", "tasks_tags"."tag_name" FROM "tasks_tag...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1073, in render
    return render_value_in_context(output, context)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\template\base.py", line 1050, in render_value_in_context
    value = str(value)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ~~~~~~~~~~~~~~^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\boundfield.py", line 108, in as_widget
    return widget.render(
           ~~~~~~~~~~~~~^
        name=self.html_initial_name if only_initial else self.html_name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        renderer=self.form.renderer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\contrib\admin\widgets.py", line 329, in get_context
    "rendered_widget": self.widget.render(name, value, attrs),
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\widgets.py", line 278, in render
    context = self.get_context(name, value, attrs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\widgets.py", line 764, in get_context
    context = super().get_context(name, value, attrs)
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\widgets.py", line 715, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ~~~~~~~~~~~~~~^
        name, context["widget"]["value"], attrs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\widgets.py", line 655, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
                                               ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\forms\models.py", line 1424, in __iter__
    for obj in queryset:
               ^^^^^^^^
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 518, in _iterator
    yield from iterable
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\Desktop\docs\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1577, in execute_sql
    cursor.close()
    ~~~~~~~~~~~~^^
psycopg2.errors.InvalidCursorName: ОШИБКА:  курсор "_django_curs_12784_sync_1" не существует

ERROR 2025-02-26 16:39:11,090 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 500 742467
INFO 2025-02-26 16:39:46,577 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:39:47,222 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:40:08,181 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:40:08,785 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:41:32,736 autoreload C:\Users\User\Desktop\docs\taskmanager\tasks\models.py changed, reloading.
INFO 2025-02-26 16:41:33,421 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:42:10,313 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 16:42:14,521 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 37735
INFO 2025-02-26 16:42:14,649 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:42:49,709 basehttp "POST /admin/tasks/task/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:42:49,794 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 38420
INFO 2025-02-26 16:42:49,866 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:43:15,792 basehttp "POST /admin/tasks/task/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:43:15,886 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 28295
INFO 2025-02-26 16:43:15,905 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2025-02-26 16:43:15,965 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:43:17,888 basehttp "GET /admin/tasks/task/add/ HTTP/1.1" 200 37735
INFO 2025-02-26 16:43:17,962 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:43:48,211 basehttp "POST /admin/tasks/task/add/ HTTP/1.1" 302 0
INFO 2025-02-26 16:43:48,290 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 29118
INFO 2025-02-26 16:43:48,366 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:43:52,731 basehttp "GET /admin/tasks/task/ HTTP/1.1" 200 28480
INFO 2025-02-26 16:43:52,898 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-02-26 16:44:13,079 basehttp "GET /tasks/status/ HTTP/1.1" 200 5714
INFO 2025-02-26 17:01:53,894 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:01:53,899 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:01:54,802 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:01:54,802 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:02:20,293 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:02:20,308 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:02:20,963 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:02:20,977 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:02:39,846 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:02:39,856 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:02:40,499 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:02:40,499 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:02:46,621 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:02:46,637 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:02:47,300 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:03:12,639 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:03:12,650 autoreload C:\Users\User\Desktop\docs\taskmanager\taskmanager\settings.py changed, reloading.
INFO 2025-02-26 17:03:13,298 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:03:13,298 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:04:23,054 basehttp "GET /tasks/status/ HTTP/1.1" 200 204
INFO 2025-02-26 17:04:24,369 basehttp "GET /tasks/status/ HTTP/1.1" 200 204
INFO 2025-02-26 17:05:00,415 basehttp "GET /tasks/status/ HTTP/1.1" 200 204
WARNING 2025-02-26 17:05:30,566 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:05:30,567 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
INFO 2025-02-26 17:05:39,628 basehttp "GET /tasks/tasks/ HTTP/1.1" 200 8191
WARNING 2025-02-26 17:07:53,900 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:07:53,901 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:07:55,453 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:07:55,454 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
INFO 2025-02-26 17:12:05,908 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 17:12:21,352 basehttp "GET /tasks/tasks/ HTTP/1.1" 200 8191
WARNING 2025-02-26 17:20:48,047 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:20:48,048 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:22:25,259 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:22:25,260 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:22:50,469 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:22:50,470 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:33:03,724 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:33:03,725 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:33:38,474 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:33:38,475 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:33:42,424 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:33:42,425 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:33:43,718 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:33:43,719 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
INFO 2025-02-26 17:34:06,751 basehttp "GET /tasks/status/ HTTP/1.1" 200 5714
WARNING 2025-02-26 17:40:01,290 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:40:01,291 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:40:02,902 log Forbidden: /tasks/tasks/
WARNING 2025-02-26 17:40:02,902 basehttp "GET /tasks/tasks/ HTTP/1.1" 403 58
WARNING 2025-02-26 17:40:42,726 log Not Found: /tasks/tasks//
WARNING 2025-02-26 17:40:42,726 basehttp "GET /tasks/tasks// HTTP/1.1" 404 3731
WARNING 2025-02-26 17:40:44,813 log Not Found: /tasks/tasks//
WARNING 2025-02-26 17:40:44,815 basehttp "GET /tasks/tasks// HTTP/1.1" 404 3731
WARNING 2025-02-26 17:41:10,897 log Not Found: /tasks/tasks//
WARNING 2025-02-26 17:41:10,898 basehttp "GET /tasks/tasks// HTTP/1.1" 404 3731
